### ISSUE TITLE
Play Next Button

### ISSUE THREAD

**Issue by Divyansh-Singhal** [Techno-Developers-Team/Musicano#1]
Play Next Button is not working. Check its functionality and make it work.

**Comment by developerNd** [comment]
Hii @Divyansh-Singhal I have checked this issue assign me I will solve this

**Comment by Divyansh-Singhal** [comment]
Assigned @developerNd

**Comment by Divyansh-Singhal** [comment]
->Autoplay song when button is clicked.
->Pause icon show on play/pause after content is played.

**Comment by Divyansh-Singhal** [comment]
Hacktoberfest-Accepted
