### ISSUE TITLE
Javascript errors 

### ISSUE THREAD

**Issue by developerNd** [Techno-Developers-Team/Musicano#10]
code has some  errors in js functions  

![Screenshot 2023-10-04 155840](https://github.com/Techno-Developers-Team/Musicano/assets/91623104/f2f0f57a-36c0-44a9-a64d-c1a0bca71f89)

**Comment by developerNd** [comment]
Assign this task to me I will solve this issue

**Comment by Divyansh-Singhal** [comment]
Assigned

**Comment by Mstanic05** [comment]
Assign this to me please!
