### ISSUE TITLE
Volume button issues

### ISSUE THREAD

**Issue by Divyansh-Singhal** [Techno-Developers-Team/Musicano#13]
Volume button works only when click is released. Change it to change volume on slide. Click does not affect it.

**Comment by HamnaJabbar** [comment]
Hi @Divyansh-Singhal !Could you plz assign this issue to me?

**Comment by Divyansh-Singhal** [comment]
Assigned

**Comment by HamnaJabbar** [comment]
hi @Divyansh-Singhal !I have done  the task and PR. Have a look, Thankyou.
