### ISSUE TITLE
Play previous Button

### ISSUE THREAD

**Issue by Divyansh-Singhal** [Techno-Developers-Team/Musicano#2]
Play Previous button is not working. Check the functionality and make it working.

**Comment by developerNd** [comment]
Hello @Divyansh-Singhal  Assign me this issue I will solve this

**Comment by barkhayadav12** [comment]
Hi, I would like to work on this issue. Can you please assign it to me?

**Comment by Divyansh-Singhal** [comment]
Assigned to @barkhayadav12 .

@developerNd you are assigned to another one.

**Comment by Divyansh-Singhal** [comment]
> Assigned to @barkhayadav12 .
> 
> @developerNd you are assigned to another one.

@barkhayadav12 Buttons are working just do the following:

->Autoplay song when button is clicked.
->Pause icon show on play/pause after content is played.

**Comment by Divyansh-Singhal** [comment]
@barkhayadav12 

Try to change the image of songs by uploading into images folder. Also try to change the background according to color of image. All previous work has been done.

**Comment by barkhayadav12** [comment]
Hi @Divyansh-Singhal, I have made the changes. I didn't change the background image because the present background image was looking much better. Can you please check it
