### ISSUE TITLE
Page not responsive

### ISSUE THREAD

**Issue by developerNd** [Techno-Developers-Team/Musicano#5]
page is not responsive Mobile view not good 
![Screenshot 2023-10-01 233843](https://github.com/Techno-Developers-Team/Musicano/assets/91623104/de2578ea-9401-44f5-820c-ff028fbc5cf5)

**Comment by developerNd** [comment]
@Divyansh-Singhal  I wil make it more responsive

**Comment by Divyansh-Singhal** [comment]
Okay.
